kind: pipeline
name: images
type: kubernetes

steps:
- name: build
  image: plugins/docker
  environment:
  settings:
    purge: false
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: zillownyc/kubectl
    build_args:
    - KUBECTL_VERSION=v1.17.6
    - AWS_CLI_VERSION=1.18.54
    tags:
    - latest
    - "1.17.6"
    - "1.17"

trigger:
  event:
  - push
  branch:
  - master
